apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: task-manager
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 4000
      targetPort: 4000
      name: http
